---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-parson-three
  labels:
    app: java-parson-three
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-parson-three
  template:
    metadata:
      labels:
        app: java-parson-three
    spec:
      containers:
        - name: java-parson-three
          image: docker.io/parsontodd/java-parson-three:latest
          ports:
            - containerPort: 8080